adv-interval: 5
average-factor: 50
batch-size: 8
blindspot-rate: 0.05
cnn-base-channel: 8
dataset: datasets/PA_2081b
gan-lambda: 2
gpu: true
image-channel: 1
image-extension: tif
iter-per-epoch: 250
iterations: 50000
learning-rate: 0.0001
load-weights: null
loss-gain: 1000
norm-range:
- 5420
- 44945
norm-range-target:
- 6265
- 38565
only-pixel-loss: true
percep-lambda: 0.2
resolution: 512
test-interval: 5
threads: 32
up-scale-factor: 2
