gpu : True
iterations : 80000
iter-per-epoch : 600
batch-size : 8
learning-rate : 0.0002
image-channel : 1
blindspot-rate : 0.05
average-factor : 50
resolution : 512
up-scale-factor : 2
cnn-base-channel : 8
norm-range : [0, 65535]
image-extension : tif
threads : 8
test-interval : 1
loss-gain : 100
gan-lambda : 2
percep-lambda : 0.05
adv-interval : 5
only-pixel-loss : False
dataset : 'datasets/PA_2081b_part2'
load-weights : '2022-07-16_19-15-40'